camping_project/camping_app/urls.py
from django.urls import path, re_path
from . import views
from .views import CampImagesDetailView

urlpatterns = [
    path('', views.index, name='index'),
    path('camping/list/', views.camping_list, name='camping_list'),
    path('camping/camping_detail/<str:camp_no>/', views.camping_detail, name='camping_detail'),
    path('camping/insert/', views.camping_insert, name='camping_form'),
    path('camp_images/<int:pk>/', CampImagesDetailView.as_view(), name='camp_images_detail'),
    path('camping/safety/', views.camping_safety, name='camping_safety'),
    path('camping/search/location', views.camping_search_location, name='camping_search_location'),
    # path('camping/search/result/', views.camping_search, name='camping_search'),
    re_path(r'^camping/search_result/(?P<keyword>[\wㄱ-ㅎㅏ-ㅣ가-힣]+)?/(?P<c_do>[\wㄱ-ㅎㅏ-ㅣ가-힣]+)?/(?P<theme>[\wㄱ-ㅎㅏ-ㅣ가-힣]+)?/?$', views.camping_search, name='camping_search'),
    # path('camping/search/result/', views.camping_search_result, name='camping_search_result'),
    path('camping/detail_intro/<int:camp_no>', views.detail_intro, name='detail_intro'),
    path('camping/detail_text/<int:camp_no>', views.detail_text, name='detail_text'),
    path('camping/detail_review/<int:camp_no>', views.detail_review, name='detail_review'),
    path('camping/detail_weather/', views.detail_weather, name='detail_weather'),
    path('camping/detail_map/<int:camp_no>', views.detail_map, name='detail_map'),
    path('camping/book/<str:camp_no>/' , views.camping_book, name='camping_book'),
    path('camping/review/<str:camp_no>/' , views.camping_review, name='camping_review'),
    path('camping/secondhanded/', views.camping_secondhanded, name='camping_secondhanded'),
    path('camping/camping_new_list/', views.camping_new_list, name='camping_new_list'),
    path('camping/camping_new_detail/<str:camp_no>', views.camping_new_detail, name='camping_new_detail'),
]

camping_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("camping_app.urls")),
    path('users/', include("users_app.urls"))
    ]

camping_project/camping_app/models.py
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class Booking(models.Model):
    book_no = models.AutoField(primary_key=True)
    book_date = models.DateTimeField()
    stay_date = models.DateTimeField()
    camp_no = models.ForeignKey('CampInfo', models.DO_NOTHING, db_column='camp_no')
    id = models.ForeignKey('UsersAppUser', models.DO_NOTHING, db_column='id')

    class Meta:
        managed = False
        db_table = 'booking'


class CampFacInfo(models.Model):
    camp_no = models.OneToOneField('CampInfo', models.DO_NOTHING, db_column='camp_no', primary_key=True)
    camp_main_fac = models.CharField(max_length=100, blank=True, null=True)
    camp_etc_info = models.CharField(max_length=45, blank=True, null=True)
    camp_brazier = models.CharField(max_length=10, blank=True, null=True)
    camp_safe_fac = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'camp_fac_info'


class CampInfo(models.Model):
    camp_no = models.AutoField(primary_key=True)
    camp_name = models.CharField(max_length=100, blank=True, null=True)
    camp_s_tt = models.CharField(max_length=200, blank=True, null=True)
    camp_tag_li = models.CharField(max_length=500, blank=True, null=True)
    camp_address = models.CharField(max_length=100, blank=True, null=True)
    camp_call = models.CharField(max_length=100, blank=True, null=True)
    camp_name = models.CharField(max_length=100, blank=True, null=True)
    camp_s_tt = models.CharField(max_length=200, blank=True, null=True)
    camp_tag_li = models.CharField(max_length=500, blank=True, null=True)
    camp_address = models.CharField(max_length=100, blank=True, null=True)
    camp_call = models.CharField(max_length=100, blank=True, null=True)
    camp_environment = models.CharField(max_length=100, blank=True, null=True)
    camp_type = models.CharField(max_length=100, blank=True, null=True)
    camp_type = models.CharField(max_length=100, blank=True, null=True)
    camp_ope_period = models.CharField(max_length=100, blank=True, null=True)
    camp_ope_day = models.CharField(max_length=100, blank=True, null=True)
    camp_pagelink = models.CharField(max_length=500, blank=True, null=True)
    camp_book = models.CharField(max_length=100, blank=True, null=True)
    camp_ope_day = models.CharField(max_length=100, blank=True, null=True)
    camp_pagelink = models.CharField(max_length=500, blank=True, null=True)
    camp_book = models.CharField(max_length=100, blank=True, null=True)
    camp_itd = models.TextField(blank=True, null=True)

    def __str__(self) :
        return self.camp_name
    
    class Meta:
        managed = False
        db_table = 'camp_info'


class CampMemeberInfo(models.Model):
    camp_no = models.AutoField(primary_key=True)
    camp_name = models.CharField(max_length=100, blank=True, null=True)
    camp_s_tt = models.CharField(max_length=200, blank=True, null=True)
    camp_tag_li = models.CharField(max_length=500, blank=True, null=True)
    camp_address = models.CharField(max_length=100, blank=True, null=True)
    camp_call = models.CharField(max_length=100, blank=True, null=True)
    camp_environment = models.CharField(max_length=100, blank=True, null=True)
    camp_type = models.CharField(max_length=100, blank=True, null=True)
    camp_ope_period = models.CharField(max_length=100, blank=True, null=True)
    camp_ope_day = models.CharField(max_length=100, blank=True, null=True)
    camp_pagelink = models.CharField(max_length=500, blank=True, null=True)
    camp_book = models.CharField(max_length=100, blank=True, null=True)
    camp_itd = models.TextField(blank=True, null=True)
    id = models.ForeignKey('UsersAppUser', models.DO_NOTHING, db_column='id', blank=True, null=True)
    approve = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'camp_memeber_info'


class CampReview(models.Model):
    review_no = models.AutoField(primary_key=True)
    rev_title = models.CharField(max_length=100, blank=True, null=True)
    rev_content = models.TextField(blank=True, null=True)
    rev_date = models.DateTimeField()
    rev_rate = models.FloatField(blank=True, null=True)
    id = models.ForeignKey('UsersAppUser', models.DO_NOTHING, db_column='id', blank=True, null=True)
    camp_no = models.ForeignKey(CampInfo, models.DO_NOTHING, db_column='camp_no')

    class Meta:
        managed = False
        db_table = 'camp_review'
    
    


class CampTypePrice(models.Model):
    camp_no = models.OneToOneField(CampInfo, models.DO_NOTHING, db_column='camp_no', primary_key=True)
    camp_normal_off_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_normal_off_season_price_we = models.IntegerField(blank=True, null=True)
    camp_normal_peak_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_normal_peak_season_price_we = models.IntegerField(blank=True, null=True)
    camp_auto_off_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_auto_off_season_price_we = models.IntegerField(blank=True, null=True)
    camp_auto_peak_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_auto_peak_season_price_we = models.IntegerField(blank=True, null=True)
    camp_glam_off_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_glam_off_season_price_we = models.IntegerField(blank=True, null=True)
    camp_glam_peak_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_glam_peak_season_price_we = models.IntegerField(blank=True, null=True)
    camp_crv_off_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_crv_off_season_price_we = models.IntegerField(blank=True, null=True)
    camp_crv_peak_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_crv_peak_season_price_we = models.IntegerField(blank=True, null=True)
    camp_normal_off_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_normal_off_season_price_we = models.IntegerField(blank=True, null=True)
    camp_normal_peak_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_normal_peak_season_price_we = models.IntegerField(blank=True, null=True)
    camp_auto_off_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_auto_off_season_price_we = models.IntegerField(blank=True, null=True)
    camp_auto_peak_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_auto_peak_season_price_we = models.IntegerField(blank=True, null=True)
    camp_glam_off_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_glam_off_season_price_we = models.IntegerField(blank=True, null=True)
    camp_glam_peak_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_glam_peak_season_price_we = models.IntegerField(blank=True, null=True)
    camp_crv_off_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_crv_off_season_price_we = models.IntegerField(blank=True, null=True)
    camp_crv_peak_season_price_wd = models.IntegerField(blank=True, null=True)
    camp_crv_peak_season_price_we = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'camp_type_price'


class CampUtility(models.Model):
    camp_no = models.OneToOneField(CampInfo, models.DO_NOTHING, db_column='camp_no', primary_key=True)
    electric = models.IntegerField(blank=True, null=True)
    wifi = models.IntegerField(blank=True, null=True)
    firewood = models.IntegerField(blank=True, null=True)
    warm_water = models.IntegerField(blank=True, null=True)
    walking_load = models.IntegerField(blank=True, null=True)
    sports_ground = models.IntegerField(blank=True, null=True)
    market = models.IntegerField(blank=True, null=True)
    water_playground = models.IntegerField(blank=True, null=True)
    athletic_fac = models.IntegerField(blank=True, null=True)
    adv_ground = models.IntegerField(blank=True, null=True)
    trampoline = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'camp_utility'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey('UsersAppUser', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:

camping_project/camping_app/forms.py
from django import forms
from .models import CampMemeberInfo

class CampingForm(forms.ModelForm):
    class Meta:
        model = CampMemeberInfo
        fields = (
            'camp_name',
            'camp_s_tt',
            'camp_tag_li',
            'camp_address',
            'camp_call',
            'camp_environment',
            'camp_type',
            'camp_ope_period',
            'camp_ope_day',
            'camp_pagelink',
            'camp_book',
            'camp_itd',
            'id',
            'approve'
            )

camping_project/camping_app/templates/camping_app/camp_book.html
{% extends 'base.html' %}
{% block content %}
<style>
  html,
  body {
      padding: 0;
      margin: 0;
      font-family: 'Nanum Gothic', '나눔고딕', Dotum, '돋움', Helvetica, AppleGothic, Sans-serif, 'Tahoma', 'MS PGothic';
      color: #626262;
      letter-spacing: -1px;
      height: 100%;
  }
  select {
    font-family: inherit;
  }
  #form_tbl {
      width: 500px;
      margin: 0 auto;
  }
  #form_tbl th {
      background-color: transparent;
      color:black;
      text-align: left;
      width: 40%;
      padding-bottom: 5px;
  }
  #form_tbl td {
    padding-bottom: 15px;
  }
  label {
      font-weight: bold;
      color: black;
      display: inline-block;
      width: 100%;
  }
  input[type="text"]#id_rev_title,
  input[type="number"]#id_rev_rate,
  input[type="date"]#id_rev_date {
      width: 100%;
      padding: 8px;
      /* margin-bottom: 10px; */
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
      font-family: inherit;
      box-shadow: none;
  }
  textarea,
  select {
      width: 100%;
      padding: 8px;
      /* margin-bottom: 10px; */
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
  }
  button#form_btn {
      background-color: #007BFF;
      color: white;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-family: inherit;
      margin-bottom: 35px;
  }
  tr {
        margin-bottom: 10px;
    }
    /* Style for the first row containing 평점 and 사용자ID */
    tr.first-row {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    /* Style for 평점 and 사용자ID labels */
    th.rate-id-label {
        text-align: left;
    }
</style>
<script>
  window.onload = function() {
    // 'td' 요소를 선택합니다.
    var tdElements = document.getElementsByTagName('td');

    // 각 'td' 요소에 대해,
    for (var i = 0; i < tdElements.length; i++) {
        var td = tdElements[i];

        // 'td' 요소의 모든 자식 노드에 대해,
        for (var j = 0; j < td.childNodes.length; j++) {
            var node = td.childNodes[j];

            // 만약 노드가 텍스트 노드이고, 그 텍스트가 '">'를 포함하고 있다면,
            if (node.nodeType === Node.TEXT_NODE && node.textContent.includes('">')) {
                // 그 노드를 제거합니다.
                td.removeChild(node);
            }
        }
    }
};
</script>
<h2 style="font-family: 'Nanum Gothic'; color: black; margin : 30px 0 40px 0;">캠핑 예약</h2>

<form method="post">
    {% csrf_token %} 
    <!-- # form 취약한 해킹코드 방지, 입력한 다음 값 못들어오도록 막아줌 -->
        <table id="form_tbl">    
      <tr>
        <th><label for="id_book_date">CHECK-IN</label></th>
        <td>
          <input type="date" name="book_date" required id="id_book_date" style="font-family: inherit;">
        </td>
      </tr>
    
      <tr>
        <th><label for="id_stay_date">CHECK-OUT</label></th>
        <td>
          
          <input type="date" name="stay_date" required id="id_stay_date" style="font-family: inherit;">
          
          
        </td>
      </tr>
    
      <tr>
        <th><label for="id_camp_no">캠핑장이름 </label></th>
        <td>
            <select name="camp_no" required id="id_camp_no" style="font-family: inherit;">
                <option value="{{forms.camp_no}}">>확인필수!</option>
            </select>
          <!-- <input type="text" name="camp_no" value="{{forms.camp_no}}" required id="id_camp_no">   -->
        </td>
      </tr>
    
      <tr style="display: none;">
        <th><label for="id_id">사용자ID</label></th>
        <td>
          
          <select name="id" required id="id_id" style="font-family: inherit;">
      <option value="{{user.id}}" selected>{{user.username}}</option>
    
    </select>
          
        </td>
      </tr>
    </table><br>
    <button id="form_btn" type="submit">등록</button>
</form>
{% endblock content %}

camping_project/camping_app/templates/camping_app/camping_review.html
{% extends 'base.html' %}
{% block content %}
<style>
  html,
  body {
      padding: 0;
      margin: 0;
      font-family: 'Nanum Gothic', '나눔고딕', Dotum, '돋움', Helvetica, AppleGothic, Sans-serif, 'Tahoma', 'MS PGothic';
      color: #626262;
      letter-spacing: -1px;
      height: 100%;
  }
  select {
    font-family: inherit;
  }
  #form_tbl {
      width: 500px;
      margin: 0 auto;
  }
  #form_tbl th {
      background-color: transparent;
      color:black;
      text-align: left;
      width: 40%;
      padding-bottom: 5px;
  }
  #form_tbl td {
    padding-bottom: 15px;
  }
  label {
      font-weight: bold;
      color: black;
      display: inline-block;
      width: 100%;
  }
  input[type="text"]#id_rev_title,
  input[type="number"]#id_rev_rate,
  input[type="date"]#id_rev_date {
      width: 100%;
      padding: 8px;
      /* margin-bottom: 10px; */
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
      font-family: inherit;
      box-shadow: none;
  }
  textarea,
  select {
      width: 100%;
      padding: 8px;
      /* margin-bottom: 10px; */
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
  }
  button#form_btn {
      background-color: #007BFF;
      color: white;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-family: inherit;
      margin-bottom: 35px;
  }
  tr {
        margin-bottom: 10px;
    }
    /* Style for the first row containing 평점 and 사용자ID */
    tr.first-row {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    /* Style for 평점 and 사용자ID labels */
    th.rate-id-label {
        text-align: left;
    }
</style>
<script>
  window.onload = function() {
    // 'td' 요소를 선택합니다.
    var tdElements = document.getElementsByTagName('td');

    // 각 'td' 요소에 대해,
    for (var i = 0; i < tdElements.length; i++) {
        var td = tdElements[i];

        // 'td' 요소의 모든 자식 노드에 대해,
        for (var j = 0; j < td.childNodes.length; j++) {
            var node = td.childNodes[j];

            // 만약 노드가 텍스트 노드이고, 그 텍스트가 '">'를 포함하고 있다면,
            if (node.nodeType === Node.TEXT_NODE && node.textContent.includes('">')) {
                // 그 노드를 제거합니다.
                td.removeChild(node);
            }
        }
    }
};
</script>
<h2 style="font-family: 'Nanum Gothic'; color: black; margin : 30px 0 40px 0;">여행은 어떠셨나요?</h2>
<form method="post">
    {% csrf_token %}
    <!-- # form 취약한 해킹코드 방지, 입력한 다음 값 못들어오도록 막아줌 -->
    <table id="form_tbl">
      <tr>
        <th><label for="id_camp_no">캠핑장 이름</label></th></tr>
        <tr>
        <td>
            <select name="camp_no" required id="id_camp_no">
              <option value="{% autoescape on %}{{rform.camp_no}}{% endautoescape %}"></option>
            </select>
        </td>
      </tr>
      <tr>
        <th><label for="id_rev_date">작성일</label></th></tr>
        <tr>
        <td>
          <input type="date" name="rev_date" required id="id_rev_date" readonly>
          <script>document.getElementById('id_rev_date').value = new Date().toISOString().substring(0, 10)</script>
          </td>
      </tr>
      <tr>
        <th><label for="id_rev_title">제목</label></th>
      </tr>
        <tr>
          <td>
            <input type="text" name="rev_title" maxlength="100" id="id_rev_title">
          </td>
        </tr>
        <tr>
          <th><label for="id_rev_rate">평점</label></th></tr>
          <tr>
          <td>
            <input type="number" name="rev_rate" step="any" id="id_rev_rate"
            max="5" min="0" value="5">
          </td>
        </tr>
  <tr>
    <th><label for="id_rev_content">리뷰 내용</label></th>
    </tr>
    <tr>
    <td>
      <textarea name="rev_content" cols="40" rows="10" id="id_rev_content" style="font-family: inherit;">
</textarea>
    </td>
  </tr>
  <tr style="display: none;">
    <th><label for="id_id">사용자ID</label></th>
    <td>
        <select name="id" id="id_id">
            <option value="{{user.id}}" selected>{{user.username}}</option>
        </select>
    </td>
  </tr>
    </table><br>
    <button id="form_btn" type="submit">등록</button>
</form>
{% endblock content %}

camping_project/camping_app/templates/camping_app/camping_safety.html
{% extends 'base.html' %}

{% block content %}   

    <h3>캠핑시 안전수칙</h3>

    <div id='wrap'>
        <div id='slide'>
            <ul id='safetyrules'>
                <li calss='safetyrule'>안전수칙1 #영상</li>
                <li calss='safetyrule'>안전수칙2 #영상</li>
                <li calss='safetyrule'>안전수칙3 #영상</li>
                <li calss='safetyrule'>안전수칙4 #영상</li>
            </ul>
        </div>
    </div>

{% endblock content %}

camping_project/camping_app/templates/camping_app/camping_search_location.html
{% extends 'base.html' %}
{% block content %}   

    <h2>내 위치에서 가까운 캠핑장</h2>
    <div id='wrap'>

        <br><br>
        <table id="camping_list">
            <tr>
                <th>번호</th>
                <th>캠핑장</th>
                <th>주소</th>
                <th>전화번호</th>
                <th>캠핑장 환경</th>
                <th>캠핑장 유형</th>
                <th>운영기간</th>
                <th>운영일</th>
            </tr>
            {% for camp in campings %}
            <tr>
                <td><a href="{% url 'camping_detail' camp.camp_no %}">{{ camp.camp_no }}</a></td>
                <td>{{ camp.camp_name }}</td>
                <td>{{ camp.camp_address}}</td>
                <td>{{ camp.camp_call}}</td>
                <td>{{ camp.camp_environment }}</td>
                <td>{{ camp.camp_type }}</td>
                <td>{{ camp.camp_ope_period }}</td>
                <td>{{ camp.camp_ope_day }}</td>
                {% comment %} <td><a href="{% url 'camping_update' camp.camp_no %}">
                    <button class='btn'>수정요청</button></a></td>
                <td><a href="{% url 'camping_QnA' camp.camp_no %}">
                    <button class='btn'>문의하기</button></a></td> {% endcomment %}
            </tr>
            {% endfor %}
        </table>

    </div>
{% endblock content %}

camping_project/camping_app/templates/camping_app/camping_secondhanded.html
{% extends 'base.html' %}
{% load static %}
{% block content %}   

<h2>중고물품 거래소</h2>

<p>
준비중입니다. 기다려주세요!
</p>

{% endblock content %}

camping_project/camping_app/templates/camping_app/detail_intro.html
<!-- <ul class="image-list">
    <li class="col_03 img_box">
      <img
        src="{{ image_links.col1_img_link }}"
        class="imgFit"
        alt="캠핑장소개 이미지"
      />
    </li>
    <li class="col_03 img_box">
      <img
        src="{{ image_links.col2_img_link }}"
        class="imgFit"
        alt="캠핑장소개 이미지"
      />
    </li>
    <li class="col_03 img_box">
      <img
        src="{{ image_links.col3_img_link }}"
        class="imgFit"
        alt="캠핑장소개 이미지"
      />
    </li>
  </ul> -->

{% if image_links %}
    <ul class="image-list">
        <li class="col_03 img_box">
            <img src="{{ image_links.col1_img_link }}" class="imgFit" alt="캠핑장소개 이미지">
        </li>
        <li class="col_03 img_box">
            <img src="{{ image_links.col2_img_link }}" class="imgFit" alt="캠핑장소개 이미지">
        </li>
        <li class="col_03 img_box">
            <img src="{{ image_links.col3_img_link }}" class="imgFit" alt="캠핑장소개 이미지">
        </li>
    </ul>
{% else %}
    <p>해당하는 데이터가 없습니다.</p>
{% endif %}

<!-- {% if camping %}
  <p class="camp_intro_txt">
    <span>{{ camping.camp_itd }}</span>
  </p>
{% else %}
  <p>해당하는 데이터가 없습니다.</p>
{% endif %} -->

{% if camping.camp_itd %}
  <p class="camp_intro_txt">
    <span>{{ camping.camp_itd }}</span>
  </p>
{% endif %}